### ISSUE TITLE
yarn companion-module-build errors with \\fnm_multishells\\28524_1719311514768\\node.exe: not found.  Yet node.exe exists.

### ISSUE THREAD

**Issue by paulstec** [Schniz/fnm#1186]
Getting node.exe not found, yet it exists in that fnm_multishells directory and over 30 others.

Running on Windows 11 in Visual Studio Code.

`PS C:\PaulProjects\companion> yarn companion-module-build
Building for: C:\PaulProjects\companion
Tools path: C:\PaulProjects\companion\node_modules\@companion-module\tools
Framework path: C:\PaulProjects\companion\node_modules\@companion-module\base
$ yarn run -B webpack -c C:/PaulProjects/companion/node_modules/@companion-module/tools/webpack.config.cjs --env $'ROOT=C:\\PaulProjects\\companion'
/mnt/c/Users/pauls/AppData/Local/Temp/xfs-9ce851f7/yarn: 2: exec: C:\Users\pauls\AppData\Local\fnm_multishells\28524_1719311514768\node.exe: not found
file:///C:/PaulProjects/companion/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);        
                         ^

ProcessOutput [Error]: /mnt/c/Users/pauls/AppData/Local/Temp/xfs-9ce851f7/yarn: 2: exec: C:\Users\pauls\AppData\Local\fnm_multishells\28524_1719311514768\node.exe: not found
    at file:///C:/PaulProjects/companion/node_modules/@companion-module/tools/scripts/build.js:47:8 
    exit code: 127 (Command not found)
    at ChildProcess.<anonymous> (file:///C:/PaulProjects/companion/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:350:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:128:17) {
  _code: 127,
  _signal: null,
  _stdout: '',
  _stderr: '/mnt/c/Users/pauls/AppData/Local/Temp/xfs-9ce851f7/yarn: 2: exec: C:\\Users\\pauls\\AppData\\Local\\fnm_multishells\\28524_1719311514768\\node.exe: not found\n',
  _combined: '/mnt/c/Users/pauls/AppData/Local/Temp/xfs-9ce851f7/yarn: 2: exec: C:\\Users\\pauls\\AppData\\Local\\fnm_multishells\\28524_1719311514768\\node.exe: not found\n'
}

Node.js v18.20.3`

**Comment by paulstec** [comment]
Some articles suggest looking at the PATH.  Posting it here so perhaps someone can tell if that is contributing to the problem.

C:\Users\pauls>echo %path%
C:\Python310\Scripts\;C:\Python310\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft Network Monitor 3\;C:\ProgramData\chocolatey\bin;C:\Users\pauls\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\dotnet\;C:\Program Files\dotnet\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files\HP\HP One Agent;C:\Program Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\Users\pauls\AppData\Local\Microsoft\WindowsApps;C:\Users\pauls\AppData\Local\Programs\Fiddler;C:\Users\pauls\AppData\Local\Programs\Microsoft VS Code\bin;;C:\Users\pauls\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Nmap;C:\Users\pauls\AppData\Local\Microsoft\WindowsApps;C:\Users\pauls\AppData\Local\Microsoft\WinGet\Packages\Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe;

**Comment by Schniz** [comment]
Closing this — it's been open for a while without activity. If you're still seeing this on a recent version, feel free to reopen.

---

*This message was written by AI. Sorry it's not personal, but it's helping me maintain this project. Feel free to disagree with the statement and reopen the issue if needed.*
