### ISSUE TITLE
Issues in fish shell

### ISSUE THREAD

**Issue by gf3** [Schniz/fnm#356]
```
fnm 1.22.8
fish, version 3.1.2
```

this is how i'm configuring fnm:

```fish
if type -q fnm
  fnm env --shell fish --use-on-cd | source
  fnm completions --shell fish | source
end
```

i get the following errors indeterminately when starting a new shell:

![2021-01-05T13:16:04,155070927-05:00](https://user-images.githubusercontent.com/18397/103684080-020ca980-4f59-11eb-8eb9-f736e0fa1e1f.png)

![2021-01-05T13:17:39,683836653-05:00](https://user-images.githubusercontent.com/18397/103684046-f9b46e80-4f58-11eb-9c22-a91e4decc5e3.png)

**Comment by Schniz** [comment]
Interesting. Sorry about that. Do you know which command fails? `fnm env` or `fnm completions`?

**Comment by gf3** [comment]
@Schniz hi gal, thanks for the reply. i'm almost certain that it's the first line (`fnm env`) as i only added the second line recently and it has been happening for a little bit. please let me know if there's anything else i can do to help debug

**Comment by Schniz** [comment]
It would be best if you can create a repo with a failing GitHub action. Because I’m kinda afk at the moment and it could help me debug 😄

**Comment by Schniz** [comment]
hey, any update? 😄

**Comment by gf3** [comment]
@Schniz unfortunately i haven't had any additional time to dig into this

**Comment by gf3** [comment]
i haven't been able to create an environment in which i can reproduct, however i just had another big crash after node process ran out of heap memory in a docker container:

```
freshline-backend          |
freshline-backend          | <--- Last few GCs --->
freshline-backend          |
freshline-backend          | [50:0x56430cb830c0]  2159687 ms: Mark-sweep (reduce) 2044.0 (2054.9) -> 2043.2 (2055.2) MB, 1898.5 / 0.0 ms  (averagemu = 0.161, current mu = 0.014) allocation failure scavenge might not succeed
freshline-backend          | [50:0x56430cb830c0]  2163033 ms: Mark-sweep (reduce) 2044.3 (2052.2) -> 2043.6 (2053.2) MB, 3336.9 / 0.0 ms  (averagemu = 0.069, current mu = 0.002) allocation failure scavenge might not succeed
freshline-backend          |
freshline-backend          |
freshline-backend          | <--- JS stacktrace --->
freshline-backend          |
freshline-backend          | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: std::io::stdio::print_to
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1021:9
   3: std::io::stdio::_print
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1033:5
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: std::io::stdio::print_to
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1021:9
   3: std::io::stdio::_print
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1033:5
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: std::io::stdio::print_to
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1021:9
   3: std::io::stdio::_print
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1033:5
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~/C/g/f/arowana main• 36m 55.2s ❱
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: std::io::stdio::print_to
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1021:9
   3: std::io::stdio::_print
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1033:5
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
~/C/g/f/arowana main• 36m 55.2s ❱
error: process ID out of range

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1021:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: std::io::stdio::print_to
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1021:9
   3: std::io::stdio::_print
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/stdio.rs:1033:5
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
~/C/g/f/arowana main• 36m 55.2s ❱
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
~/C/g/f/arowana main• 36m 55.2s ❱
```

**Comment by gf3** [comment]
```
fnm 1.22.9
fish, version 3.2.1
```

**Comment by Schniz** [comment]
I can't really help if I can't reproduce. Feel free to compile from source and try to add println 😒

What I really don't understand is why we get "can't infer shell", if you provide the shell explicitly. 🤨

**Comment by Schniz** [comment]
If you have ideas and you aren't sure how to encode it in Rust, I'd be glad to help

**Comment by lkonya** [comment]
I'm using fish as well, but it works for me (although just set it up a couple of minutes ago)
```
fish, version 3.2.2
fnm 1.24.0
macOS 11.2.1
```

**Comment by Schniz** [comment]
> ```
> fnm 1.22.9
> fish, version 3.2.1
> ```

Oh, try to upgrade. Not sure it will work.



> I'm using fish as well, but it works for me (although just set it up a couple of minutes ago)

There might be something else that is configured in the shell that makes it harder to use. Not sure and can't really debug that remotely. I regularly do shell-configuration-debugging for coworkers 😃

**Comment by lkonya** [comment]
Soooo... :( 
`thread 'main' panicked at 'Unable to identify current directory: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/context.rs:69:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by brandonpittman** [comment]
@jorgebucaran 

Thanks, but per your comment in the hydro repo, I switched to nvm.fish! 😆

**Comment by MauricioRobayo** [comment]
I'm using [Tide](https://github.com/IlanCosman/tide) and got similar error unless I run the configuration only if Fish is interactive. This is the error:

```
thread 'main' panicked at 'Can't write output: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/commands/use.rs:56:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details>
<summary>Backtrace</summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: <fnm::commands::use::Use as fnm::commands::command::Command>::apply
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Can't write output: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/commands/use.rs:56:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: <fnm::commands::use::Use as fnm::commands::command::Command>::apply
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by Schniz** [comment]
Woah @MauricioRobayo I just saw your edits. Looks pretty good. Very weird that v1.22.7 does work and v1.22.8 does not, as there is [not much difference between them](https://github.com/Schniz/fnm/compare/v1.22.7...v1.22.8) 🤔 
can you confirm that it is still the case?

**Comment by trm217** [comment]
@Schniz Thanks for your fast response :)

**Comment by trm217** [comment]
For the mine time I fixed the issue with a slight adaptation of the configuration shared by @jorgebucaran.
(I added the -q flag to prevent the path to fnm being written into the console when running the type command)

```
if type fnm -q && status is-interactive 
  fnm env --shell fish --use-on-cd | source
  fnm completions --shell fish | source
end
```

**Comment by jasonkuhrt** [comment]
I'm having this issue. Was working. Noticed today the problem. Not sure what changed.

**Comment by guilhermedeandrade** [comment]
Getting the same error when I cd into a node repository. That's strange because it started happening today 🤔 

`thread 'main' panicked at 'Can't write output: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/commands/use.rs:92:13`

macOS 12.6 (M1 Pro)
fnm 1.31.1
fish, version 3.5.1
tide, version 5.5.1

**Comment by woeps** [comment]
[This comment in another repos's issue](https://github.com/IlanCosman/tide/issues/143#issuecomment-944421587) seems to solve it. :tada:

Change `~/.config/fish/conf.d/fnm.fish` to:
```
status is-interactive && fnm env --use-on-cd | source
```

Note: I have absolutely no clue what `status is-interactive` actually does. But this solved the issue for me and I'm now using fnm happily on fish + tide again. :smile:
