### ISSUE TITLE
command node not found 

### ISSUE THREAD

**Issue by ri7nz** [Schniz/fnm#427]
## Issue
I have been following how to integrate `fnm` with `zsh` and I use `fnm` normally but when I quit from `vim`, `node command not found`, so I check `fnm current`, it's show the current version of `node` but can execute command from node. 

## Produces
```shell
❯ node -v
zsh: command not found: node
❯ fnm current
v14.16.0
❯ fnm use v14.16.0
❯ fnm list
* v12.22.0
* v14.16.0 default
* system
❯ fnm current
v14.16.0
❯ node -v
zsh: command not found: node
```
### OS Information 
```shell
OS: macOS 11.2.3 20D91 x86_64
Host: MacBookPro15,4
Kernel: 20.3.0
Uptime: 2 days, 9 hours, 13 mins
Packages: 97 (brew)
Shell: zsh 5.8
Resolution: 1440x900@2x
DE: Aqua
WM: Rectangle
Terminal: iTerm2
Terminal Font: FiraCodeNerdFontCompleteM-Regular 11
CPU: Intel i5-8257U (8) @ 1.40GHz
GPU: Intel Iris Plus Graphics 645
Memory: 5641MiB / 8192MiB
```
### Zsh Configuration 
```
 277   │ eval "$(fnm env)"
 278   │
 279   │ # it's brew but update after install packages
 280   │ function bruw() {
 281   │     HOMEBREW_NO_AUTO_UPDATE=1 brew "$@" && brew update
 282   │ }
 283   │
 284   │ alias ls="ls -G"
 285   │ alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
 286   │
 287   │ alias cat=bat
 288   │ alias l='ls -l'
 289   │ alias la='ls -a'
 290   │ alias lla='ls -la'
 291   │ alias lt='ls --tree'
```
[See detail zsh configuration here](https://github.com/ri7nz/.dotifiles)

**Comment by Schniz** [comment]
Can you please show me the output of the following commands:

```
echo $PATH
env | grep FNM_
```

**Comment by ri7nz** [comment]
@Schniz  

```shell
❯ echo $PATH
/Users/r17/perl5/bin:/Users/r17/.yarn/bin:/Users/r17/.config/yarn/global/node_modules/.bin:/var/folders/p8/p4d4n5l91t5g4cjrv4kp9t1h0000gp/T/fnm_multishells/7940_1617982869850/bin:/Users/r17/.zinit/polaris/bin:/Users/r17/.fnm:/usr/local/bin:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/bin/core_perl/:/Users/r17/.local/bin:/Users/r17/scripts/bin:/usr/local/opt/fzf/bin:/Users/r17/go/bin:/usr/local/opt/go/libexec/bin
❯ env G FNM_
FNM_HOME=/Users/r17/.fnm
FNM_MULTISHELL_PATH=/var/folders/p8/p4d4n5l91t5g4cjrv4kp9t1h0000gp/T/fnm_multishells/7940_1617982869850
FNM_DIR=/Users/r17/.fnm
FNM_LOGLEVEL=info
FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
FNM_ARCH=x64
❯ node -v
zsh: command not found: node
```

**Comment by ri7nz** [comment]
@Schniz  

maybe this is will help how to solve this issue

```zsh
❯ fnm list
* v12.22.0
* v14.16.0
* v14.16.1
* system
❯ for version in $(fnm list); do
case $version in
\*|system) ;;
*) echo "using node $version" && RUST_BACKTRACE=full fnm exec --using=$version node --version;;
esac
done;
using node v12.22.0
thread 'main' panicked at 'Can't spawn program: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/commands/exec.rs:70:14
stack backtrace:
   0:        0x100be981e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
   1:        0x100c295ee - core::fmt::write::h14dac7cadec1cc70
   2:        0x100be937a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
   3:        0x100c06b39 - std::panicking::default_hook::{{closure}}::h350fee0bf60f2674
   4:        0x100c066ab - std::panicking::default_hook::h0b4e3bc46e6dcb8d
   5:        0x100c070ca - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
   6:        0x100be9fe5 - std::panicking::begin_panic_handler::{{closure}}::h7a7b30fd1c313876
   7:        0x100be9968 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e099be83c81509d
   8:        0x100c06c43 - _rust_begin_unwind
   9:        0x100c374af - core::panicking::panic_fmt::h4f63e4f6b62b650b
  10:        0x100c37015 - core::result::unwrap_failed::hc2a56d017349147e
  11:        0x1008616bf - fnm::commands::command::Command::call::hcfbb5e46bb897282
  12:        0x10087fd15 - fnm::cli::SubCommand::call::hf453d893efaf23b3
  13:        0x10087d7b1 - fnm::main::h62fde99382031ed2
  14:        0x10085de3a - std::sys_common::backtrace::__rust_begin_short_backtrace::h300dff8753d5b931
  15:        0x10085de6c - std::rt::lang_start::{{closure}}::hfe46e79d78ea463e
  16:        0x100c0b5e0 - std::rt::lang_start_internal::hf4b96bfc8c02c8b0
  17:        0x10087de49 - _main
using node v14.16.0
thread 'main' panicked at 'Can't spawn program: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/commands/exec.rs:70:14
stack backtrace:
   0:        0x10d67e81e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
   1:        0x10d6be5ee - core::fmt::write::h14dac7cadec1cc70
   2:        0x10d67e37a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
   3:        0x10d69bb39 - std::panicking::default_hook::{{closure}}::h350fee0bf60f2674
   4:        0x10d69b6ab - std::panicking::default_hook::h0b4e3bc46e6dcb8d
   5:        0x10d69c0ca - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
   6:        0x10d67efe5 - std::panicking::begin_panic_handler::{{closure}}::h7a7b30fd1c313876
   7:        0x10d67e968 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e099be83c81509d
   8:        0x10d69bc43 - _rust_begin_unwind
   9:        0x10d6cc4af - core::panicking::panic_fmt::h4f63e4f6b62b650b
  10:        0x10d6cc015 - core::result::unwrap_failed::hc2a56d017349147e
  11:        0x10d2f66bf - fnm::commands::command::Command::call::hcfbb5e46bb897282
  12:        0x10d314d15 - fnm::cli::SubCommand::call::hf453d893efaf23b3
  13:        0x10d3127b1 - fnm::main::h62fde99382031ed2
  14:        0x10d2f2e3a - std::sys_common::backtrace::__rust_begin_short_backtrace::h300dff8753d5b931
  15:        0x10d2f2e6c - std::rt::lang_start::{{closure}}::hfe46e79d78ea463e
  16:        0x10d6a05e0 - std::rt::lang_start_internal::hf4b96bfc8c02c8b0
  17:        0x10d312e49 - _main
using node v14.16.1
thread 'main' panicked at 'Can't spawn program: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/commands/exec.rs:70:14
stack backtrace:
   0:        0x108abf81e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
   1:        0x108aff5ee - core::fmt::write::h14dac7cadec1cc70
   2:        0x108abf37a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
   3:        0x108adcb39 - std::panicking::default_hook::{{closure}}::h350fee0bf60f2674
   4:        0x108adc6ab - std::panicking::default_hook::h0b4e3bc46e6dcb8d
   5:        0x108add0ca - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
   6:        0x108abffe5 - std::panicking::begin_panic_handler::{{closure}}::h7a7b30fd1c313876
   7:        0x108abf968 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e099be83c81509d
   8:        0x108adcc43 - _rust_begin_unwind
   9:        0x108b0d4af - core::panicking::panic_fmt::h4f63e4f6b62b650b
  10:        0x108b0d015 - core::result::unwrap_failed::hc2a56d017349147e
  11:        0x1087376bf - fnm::commands::command::Command::call::hcfbb5e46bb897282
  12:        0x108755d15 - fnm::cli::SubCommand::call::hf453d893efaf23b3
  13:        0x1087537b1 - fnm::main::h62fde99382031ed2
  14:        0x108733e3a - std::sys_common::backtrace::__rust_begin_short_backtrace::h300dff8753d5b931
  15:        0x108733e6c - std::rt::lang_start::{{closure}}::hfe46e79d78ea463e
  16:        0x108ae15e0 - std::rt::lang_start_internal::hf4b96bfc8c02c8b0
  17:        0x108753e49 - _main

~                                                                                                                             02:51:30
❯
```

**Comment by Schniz** [comment]
Can you

```
ls $FNM_MULTISHELL_PATH
ls -l $FNM_MULTISHELL_PATH/bin
```

? 😃

**Comment by ri7nz** [comment]
@Schniz  
this is 
```
❯ ls $FNM_MULTISHELL_PATH
/var/folders/p8/p4d4n5l91t5g4cjrv4kp9t1h0000gp/T/fnm_multishells/25658_1618258813600
❯ ls -l $FNM_MULTISHELL_PATH/bin

ls: /var/folders/p8/p4d4n5l91t5g4cjrv4kp9t1h0000gp/T/fnm_multishells/25658_1618258813600/bin: No such file or directory
````

**Comment by Schniz** [comment]
> ❯ ls $FNM_MULTISHELL_PATH
> /var/folders/p8/p4d4n5l91t5g4cjrv4kp9t1h0000gp/T/fnm_multishells/25658_1618258813600

this is weird. can you please

```
ls -lah $FNM_MULTISHELL_PATH
```
?

**Comment by ri7nz** [comment]
@Schniz   I was uninstall all of version node cause i need to run node.js. so I install again 

```
❯ ls -lah $FNM_MULTISHELL_PATH
lrwxr-xr-x  1 r17  staff    31B Apr 13 18:45 /var/folders/p8/p4d4n5l91t5g4cjrv4kp9t1h0000gp/T/fnm_multishells/53168_1618314313734 -> /Users/r17/.fnm/aliases/default
❯ fnm list
* v10.24.1
* v14.16.1
* system
```

**Comment by ri7nz** [comment]
@Schniz I have been try to use in another machine, I found some clues. `bin` directory of node version is missing, my assume is deleted by (i dunno who deleted) in sometimes. 

- Machine information
```shell
❯ neofetch
                    'c.          r17@RG.local
                 ,xNMM.          ------------
               .OMMMMo           OS: macOS 11.2 20D64 arm64
               OMMM0,            Host: MacBookPro17,1
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 21 hours, 53 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Rectangle
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: FiraCodeNerdFontCompleteM-Regul
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1298MiB / 8192MiB
       .cooc,.    .,coo:.
```
- Heres, log 
```shell
❯ cd $TMPDIR
❯ cd fnm_multishells/
❯ ls -la
total 0
drwxr-xr-x  125 r17  staff  4000 Apr 14 18:42 .
drwx------@ 188 r17  staff  6016 Apr 14 18:38 ..
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:56 10032_1618336602964 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:59 12588_1618336763979 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:07 12926_1618384035759 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 01:58 13453_1618340311627 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:36 13718_1618396571470 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1518_1618400282785 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1584_1618400282945 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:37 16028_1618396637295 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 01:03 16421_1618337003844 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1650_1618400283103 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1716_1618400283260 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1783_1618400283420 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:09 18126_1618384177648 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    51 Apr 14 01:06 18316_1618337167669 -> /Users/r17/.fnm/node-versions/v14.16.1/installation
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1849_1618400283580 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1915_1618400283742 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 1981_1618400283900 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 13:30 20608_1618381841896 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 2068_1618400284061 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:38 2142_1618400284220 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:02 21459_1618333339944 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 13:31 21844_1618381913686 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 13:31 22486_1618381915004 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 05:38 22953_1618353480460 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    51 Apr 14 09:10 23801_1618353540747 -> /Users/r17/.fnm/node-versions/v14.16.1/installation
lrwxr-xr-x    1 r17  staff    31 Apr 14 01:10 24974_1618337426035 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:04 25402_1618333488577 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:04 2626_1618383846504 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 16:27 29100_1618392447791 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:44 29437_1618397081740 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:45 30681_1618397157956 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:46 30923_1618397165808 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:46 31210_1618397170025 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:06 31323_1618333584025 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:19 32675_1618341575720 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:21 34177_1618341684443 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:09 34317_1618333777127 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 13 23:06 35227_1618330000987 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    51 Apr 13 23:07 35645_1618330012704 -> /Users/r17/.fnm/node-versions/v14.16.1/installation
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:51 35709_1618397505222 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:26 38099_1618341961547 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:27 39175_1618342036013 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:39 4016_1618400352956 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:34 44068_1618342452257 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:34 44820_1618342479278 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:34 45426_1618342495605 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:35 45574_1618342503140 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    51 Apr 14 18:41 4567_1618400376496 -> /Users/r17/.fnm/node-versions/v14.16.1/installation
lrwxr-xr-x    1 r17  staff    31 Apr 14 01:25 45949_1618338306879 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:35 46089_1618342519281 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 03:33 4622_1618346006714 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:36 46940_1618342577128 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 02:36 47090_1618342582335 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:46 47470_1618368402658 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:22 51496_1618334520923 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:01 52449_1618394465094 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:01 54547_1618394519411 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:24 55203_1618334641244 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 13 23:15 56542_1618330535389 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    51 Apr 14 05:29 57398_1618348131036 -> /Users/r17/.fnm/node-versions/v14.16.1/installation
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:05 5741_1618383921405 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:03 58830_1618394625017 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:58 66585_1618369138919 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 03:04 69481_1618344292961 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69547_1618335121334 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69604_1618335121477 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69661_1618335121618 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69718_1618335121759 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69775_1618335121899 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69832_1618335122040 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69889_1618335122185 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 69946_1618335122324 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 70003_1618335122465 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:32 70060_1618335122606 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:19 73695_1618366780516 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:21 74599_1618399272156 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 77375_1618349604455 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 77397_1618366865335 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 77895_1618349636388 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78099_1618349637524 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78169_1618349637650 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78259_1618349637805 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78437_1618349638138 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78544_1618349638315 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78636_1618349638474 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78724_1618349638621 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 04:33 78811_1618349638766 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 15:30 79205_1618389056688 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 80718_1618366910947 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 17:20 81009_1618395634414 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 82158_1618366919100 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 82251_1618366919383 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 82318_1618366919565 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 82384_1618366919736 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 03:22 82442_1618345341952 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:21 82450_1618366919899 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 82515_1618366920058 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 82585_1618366920233 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 82808_1618366920469 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 82881_1618366920638 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:05 8293_1618383956987 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 82957_1618366920800 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83107_1618366922695 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83181_1618366922862 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83265_1618366923045 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83343_1618366923228 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83454_1618366923487 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83520_1618366923650 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83586_1618366923816 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83671_1618366924076 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83826_1618366924488 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 09:22 83919_1618366924784 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 00:42 86291_1618335758623 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 03:24 86333_1618345488541 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 13:58 86928_1618383537800 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 03:25 87398_1618345520889 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 13:59 88866_1618383563154 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:31 90321_1618399914392 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 13:59 90897_1618383576576 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 18:42 9438_1618400548053 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:01 94729_1618383677253 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:01 95868_1618383683414 -> /Users/r17/.fnm/aliases/default
lrwxr-xr-x    1 r17  staff    31 Apr 14 14:06 9889_1618383970616 -> /Users/r17/.fnm/aliases/default
❯ fnm install 12 
Installing Node v12.22.1
❯ fnm use 12
Using Node v12.22.1
❯ node -v
v12.22.1
❯ where node -v
/var/folders/xj/w8stvj556ylftz6skrb8nzp80000gp/T/fnm_multishells/9438_1618400548053/bin/node
/var/folders/xj/w8stvj556ylftz6skrb8nzp80000gp/T/fnm_multishells/90321_1618399914392/bin/node
❯ ls -la | grep 9438_1618400548053
lrwxr-xr-x    1 r17  staff    51 Apr 14 18:45 9438_1618400548053 -> /Users/r17/.fnm/node-versions/v12.22.1/installation
❯ cd /Users/r17/.fnm/node-versions/v12.22.1/installation
❯ ls # have bin include lib share (v12.22.1)
CHANGELOG.md LICENSE      README.md    bin          include      lib          share
❯ ls /Users/r17/.fnm/node-versions/v14.16.1/installation/
lib   share # nothing bin (v14.16.1) 
❯ fnm list
* v12.22.1 default
* v14.16.1
* system
❯ fnm current
v12.22.1

~/.fnm/node-versions/v12.22.1/installation                                                                                18:47:08
❯
```

**Comment by TimonVS** [comment]
I have the same issue, but the behavior is slightly different for me. Sometimes when I open a shell, or come back to a shell that has been open for a while, `node` and `npm` won't work (command not found). I noticed that the fnm_multishells bin directory in `$PATH` would actually be non-existent. Opening a new shell (new tab or running `zsh`) fixes it (uses a different fnm_multishells bin path).

<details>
<summary>Terminal output</summary>

```
λ ~/Code/Cimpress/dex-component-library/ main* node
zsh: command not found: node
λ ~/Code/Cimpress/dex-component-library/ main* echo $PATH
/Users/timon.vanspronsen/.deno/bin:/var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/6083_1642666358403/bin:/Users/timon.vanspronsen/.fnm:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/timon.vanspronsen/.deno/bin:/var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/2363_1642665296707/bin:/Users/timon.vanspronsen/.fnm
λ ~/Code/Cimpress/dex-component-library/ main* ls -la /var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/6083_1642666358403/bin
ls: /var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/6083_1642666358403/bin: No such file or directory
λ ~/Code/Cimpress/dex-component-library/ main* fnm current
none
λ ~/Code/Cimpress/dex-component-library/ main* ls $FNM_MULTISHELL_PATH
ls: /var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/6083_1642666358403: No such file or directory
λ ~/Code/Cimpress/dex-component-library/ main* ls -l $FNM_MULTISHELL_PATH/bin
ls: /var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/6083_1642666358403/bin: No such file or directory
λ ~/Code/Cimpress/dex-component-library/ main* env | grep FNM_
FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
FNM_ARCH=x64
FNM_LOGLEVEL=info
FNM_DIR=/Users/timon.vanspronsen/.fnm
FNM_MULTISHELL_PATH=/var/folders/zz/k_8ldk0d1s54527vdn3vmd4h0000gn/T/fnm_multishells/6083_1642666358403
FNM_VERSION_FILE_STRATEGY=local
```

</details

**Comment by Schniz** [comment]
yeah, I need to merge #638 because I'm using it for a while 🥲

**Comment by Schniz** [comment]
but I think it is not related to this issue

**Comment by ReAlign** [comment]
I am try `fnm default v12.22.0`, and then `node -v` is effective.

maybe should use `fnm default <version>`, not `fnm use <version>`, i am in fnm@1.28.1

**Comment by andrey-helldar** [comment]
For Windows:

You must specify the following path in the environment variables:

```
%USERPROFILE%\AppData\Roaming\fnm\aliases\default\
```

**Comment by hmstrand** [comment]
> For Windows:
> 
> You must specify the following path in the environment variables:
> 
> ```
> %USERPROFILE%\AppData\Roaming\fnm\aliases\default\
> ```

Thanks, this fixed it for me!
