### ISSUE TITLE
Crash when trying to install node version (macOS arm64)

### ISSUE THREAD

**Issue by bradleymackey** [Schniz/fnm#504]
I'm not sure when this started, but no matter the version I try to install, I'm getting this same error (even Node 16+, which has native support for Darwin ARM).

```sh
$ RUST_BACKTRACE=full fnm install 16
thread 'reqwest-internal-sync-runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Custom { kind: InvalidData, error: BadDER } }', /Users/bradley/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/async_impl/client.rs:297:65
stack backtrace:
   0:        0x10328a984 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h092059600d98bb8d
   1:        0x1032bed30 - core::fmt::write::h504ad4f4f036f81e
   2:        0x103286f40 - std::io::Write::write_fmt::h7ec6d94b3741b164
   3:        0x10329e6c8 - std::panicking::default_hook::{{closure}}::h94837360d6971e8d
   4:        0x10329e25c - std::panicking::default_hook::he9f2914f0b4457f3
   5:        0x10329eb64 - std::panicking::rust_panic_with_hook::h6b5d9a10ca9fad45
   6:        0x10328ac8c - std::panicking::begin_panic_handler::{{closure}}::haa07be57cb026bbd
   7:        0x10328aac4 - std::sys_common::backtrace::__rust_end_short_backtrace::h7bd579b4959641b2
   8:        0x10329e7b0 - _rust_begin_unwind
   9:        0x1032d0930 - core::panicking::panic_fmt::h77195cbc7d0fefb9
  10:        0x1032d0e6c - core::result::unwrap_failed::h39a5629cbfac6449
  11:        0x103132588 - reqwest::async_impl::client::ClientBuilder::build::hd2a8c6624c846942
  12:        0x1030d9938 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0355065b17300af1
  13:        0x1030be5f8 - tokio::macros::scoped_tls::ScopedKey<T>::set::h547e63a278d4ba32
  14:        0x1030cacb8 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hcac3986efc264f9f
  15:        0x1030bf2f4 - tokio::runtime::Runtime::block_on::h10c26022e0c3d3c0
  16:        0x1030f8220 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0e0f3eeddc3a0786
  17:        0x10315c0cc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0d5c89e2583f68c2
  18:        0x103287b64 - std::sys::unix::thread::Thread::new::thread_start::ha562e176cc86d64a
  19:        0x180837878 - _pthread_jit_write_protect_np
thread 'main' panicked at 'event loop thread panicked', /Users/bradley/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/client.rs:1028:5
stack backtrace:
   0:        0x10328a984 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h092059600d98bb8d
   1:        0x1032bed30 - core::fmt::write::h504ad4f4f036f81e
   2:        0x103286f40 - std::io::Write::write_fmt::h7ec6d94b3741b164
   3:        0x10329e6c8 - std::panicking::default_hook::{{closure}}::h94837360d6971e8d
   4:        0x10329e25c - std::panicking::default_hook::he9f2914f0b4457f3
   5:        0x10329eb64 - std::panicking::rust_panic_with_hook::h6b5d9a10ca9fad45
   6:        0x1030f8888 - std::panicking::begin_panic::{{closure}}::ha7965c48cb57a091
   7:        0x1030f8050 - std::sys_common::backtrace::__rust_end_short_backtrace::h7bce7984262ac922
   8:        0x1032c6fdc - std::panicking::begin_panic::ha6285e9a8c56780e
   9:        0x1032c6ff8 - reqwest::blocking::client::event_loop_panicked::hb9432acbfa5219b9
  10:        0x1030f5bac - reqwest::blocking::client::ClientBuilder::build::hea803b8d7cec9883
  11:        0x102fab380 - reqwest::blocking::get::h77d39c4f008131b2
  12:        0x102fc812c - fnm::remote_node_index::list::h5cb31bc759a280e1
  13:        0x102fbf120 - <fnm::commands::install::Install as fnm::commands::command::Command>::apply::hc289641006163065
  14:        0x102fbeb08 - fnm::commands::command::Command::call::h9e8f2e5e31ab1bba
  15:        0x102fb89cc - fnm::cli::SubCommand::call::h99ede37ec70f01c2
  16:        0x102fccc0c - fnm::main::h93d7c4916522bb18
  17:        0x102fa94d8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h775332c1efb17887
  18:        0x102fa94f4 - std::rt::lang_start::{{closure}}::h180eee359755bae2
  19:        0x1032a7b7c - std::rt::lang_start_internal::h71b868045f6d51f4
  20:        0x102fcd2e0 - _main
```

**Comment by Schniz** [comment]
Unfortunately I do now own an M1 machine, so if you can clone the repo and try debugging, that would be best. ☹️

**Comment by andretf** [comment]
just did a fresh install on my macos 11.4 and it crashes with `list-remote` as well, and it makes sense as it looks like it's used to install a version too.

**Comment by andretf** [comment]
I've just installed v1.25.0 and it's working
perhaps bug was introduced by one of the updated dependencies? https://github.com/Schniz/fnm/compare/v1.25.0...v1.26.0

**Comment by Schniz** [comment]
Can you try cloning and building with https://github.com/Schniz/fnm/pull/468 reverted and not reverted and see if it makes a difference?

**Comment by Schniz** [comment]
https://github.com/Schniz/fnm/commit/560583a1d657fe4180b42fe35979077733cb9dba this is the commit :)

**Comment by itotallyrock** [comment]
I recently heard of this tool and wanted to try it out, but ran into the same issue on my windows machine.

```
thread 'reqwest-internal-sync-runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Custom { kind: InvalidData, error: BadDER } }', C:\Users\jmeyer\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.11.3\src\async_impl\client.rs:274:65
```

Using rust 1.54 on windows with `stable-x86_64-pc-windows-msvc`.

I checked out master and the 560583a commit, and both still had the issue.

![image](https://user-images.githubusercontent.com/3466882/128938873-87346e74-1307-4e70-86d9-4955fec54b75.png)

While the parent commit, b282b40 , didn't have the issue. (ignore the permissions error as its unrelated)

![image](https://user-images.githubusercontent.com/3466882/128938224-42eb1b23-67a3-4737-a1b5-0a352b4d3d30.png)

**Comment by Schniz** [comment]
Interesting! Would you want to open a PR reverting this change?

**Comment by itotallyrock** [comment]
I just made a PR (#512) reverting it.
