### ISSUE TITLE
thread 'main' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }'

### ISSUE THREAD

**Issue by MichaelSp** [Schniz/fnm#650]
fnm fails right after installation on MacOS Montery 12.1

##### Steps to reproduce:

`brew install fnm`

```shell
$ fnm ls-remote
thread 'main' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Schniz** [comment]
does not seem to reproduce locally. seems related to https://github.com/seanmonstar/reqwest/issues/1419

**Comment by tomtomdurrant** [comment]
Can confirm I have the above issue with a non M1 macbook running intel i9 chip

**Comment by Schniz** [comment]
I have an M1 machine. Maybe we need to downgrade a reqwests version? Can some of you build it locally?

**Comment by tomtomdurrant** [comment]
Will give it a go and get back to you. Anything you're specifically looking for?

**Comment by Schniz** [comment]
Thank you!
- You can start by trying to use v1.29.0 -- https://github.com/Schniz/fnm/releases/tag/v1.29.0
- If that works, it'd be nice if you can try cloning the main branch and revert the following commit: https://github.com/Schniz/fnm/commit/8b3e48380e6db5ffcc4acc97945696317a5c5863

**Comment by tomtomdurrant** [comment]
Here's the output of the builds from the 2 commits. 


<details><summary>1c52620</summary>

``` 
  
Compiling fnm v1.29.2 (/Users/tom/dev/reproducing/fnm)
    Finished dev [unoptimized + debuginfo] target(s) in 2.84s
     Running `target/debug/fnm install --lts`
thread 'main' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::expect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1258:23
   4: reqwest::blocking::client::Client::new
             at /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:9
   5: fnm::http::get
             at ./src/http.rs:11:5
   6: fnm::remote_node_index::list
             at ./src/remote_node_index.rs:76:16
   7: <fnm::commands::install::Install as fnm::commands::command::Command>::apply
             at ./src/commands/install.rs:63:50
   8: fnm::commands::command::Command::call
             at ./src/commands/command.rs:16:15
   9: fnm::cli::SubCommand::call
             at ./src/cli.rs:79:35
  10: fnm::main
             at ./src/main.rs:41:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
</details>



<details><summary>8b3e483</summary>

```
Compiling fnm v1.29.0 (/Users/tom/dev/reproducing/fnm)
    Finished dev [unoptimized + debuginfo] target(s) in 2.57s
     Running `target/debug/fnm install --lts`
thread 'main' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::expect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1258:23
   4: reqwest::blocking::client::Client::new
             at /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:9
   5: fnm::http::get
             at ./src/http.rs:11:5
   6: fnm::remote_node_index::list
             at ./src/remote_node_index.rs:76:16
   7: <fnm::commands::install::Install as fnm::commands::command::Command>::apply
             at ./src/commands/install.rs:63:50
   8: fnm::commands::command::Command::call
             at ./src/commands/command.rs:16:15
   9: fnm::cli::SubCommand::call
             at ./src/cli.rs:79:35
  10: fnm::main
             at ./src/main.rs:41:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

Also, when I run the tests on v1.29.2 commit, the tests fail with the following 

```
failures:

---- commands::install::tests::test_set_default_on_new_installation stdout ----
thread 'commands::install::tests::test_set_default_on_new_installation' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- archive::zip::tests::test_zip_extraction stdout ----
thread 'archive::zip::tests::test_zip_extraction' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38

---- downloader::tests::test_installing_node_12 stdout ----
thread 'downloader::tests::test_installing_node_12' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38

---- remote_node_index::tests::test_list stdout ----
thread 'remote_node_index::tests::test_list' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38

---- downloader::tests::test_installing_npm stdout ----
thread 'downloader::tests::test_installing_npm' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: MissingOrMalformedExtensions }', /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/blocking/client.rs:798:38


failures:
    archive::zip::tests::test_zip_extraction
    commands::install::tests::test_set_default_on_new_installation
    downloader::tests::test_installing_node_12
    downloader::tests::test_installing_npm
    remote_node_index::tests::test_list

test result: FAILED. 18 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.74s

error: test failed, to rerun pass '--bin fnm'

```

Not sure how helpful this is, my knowledge of the rust ecosystem is _very_ limited. Let me know if there's anything else I can help with

**Comment by Schniz** [comment]
Can you tell me the last version that does work for you? We're probably going to need to do some binary search to figure out what version of `reqwest` we need to use.

Another option is to build from source without the native TLS feature. Although a PR fixing it was already merged so we better wait for reqwest to publish a new version. 🙏 

related:
* https://github.com/seanmonstar/reqwest/pull/1316

**Comment by krisan** [comment]
**macOS 12.2 / Intel**
The same issue (installed using brew or installation script):

```shell
$ uname -a
Darwin xxxxxxx 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

$ fnm -V
fnm 1.30.1
```

The same issue when build from sources using the latest master f83fc482514153d52c8da5505cddf15965f1e231

In my case I solved the issue by `"rustls-tls-native-roots"` from `reqwest` feature dependencies (also with only `default-tls` and removed `rustls*` worked):
```diff
$ git diff Cargo.toml
diff --git a/Cargo.toml b/Cargo.toml
index 33df8e1..befcf8f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -25,7 +25,7 @@ log = "0.4.14"
 env_logger = "0.9.0"
 atty = "0.2.14"
 encoding_rs_io = "0.1.7"
-reqwest = { version = "0.11.9", features = ["blocking", "json", "rustls-tls", "rustls-tls-native-roots", "brotli"], default-features = false }
+reqwest = { version = "0.11.9", features = ["blocking", "json", "rustls-tls", "brotli"], default-features = false }
 url = "2.2.2"
 sysinfo = "0.23.0"
 thiserror = "1.0.30"
```


It seems that `rustls-tls` and `rustls-tls-native-roots` features are mutually exclusive, but it is 1st time I'm building a rusty code, so I can be wrong ;-)

**Comment by barfurth** [comment]
This is still an issue even though the relevant PR in `reqwest` has been merged a while ago. Any estimate on the fix?

**Comment by krisan** [comment]
Thanks @Schniz,
I can confirm, the #671 resolved the https://github.com/Schniz/fnm/issues/650#issuecomment-1029273285 issue for me.

**Comment by tuscen** [comment]
Hi. I see that v1.31 with the fix has been released but is missing from https://crates.io.
